### ISSUE TITLE
login

### ISSUE THREAD

**Issue by okdadmin** [seriohub/velero-ui#32]
Hello,

I installed this with k8s scenario and how can I login? I don't know username and password!

Laci

**Comment by davideserio** [comment]
Hi,

I recommend using the installation via [helm](https://github.com/seriohub/velero-helm).
default user and password are [admin/admin](https://github.com/seriohub/velero-helm/blob/3651e1fe43a045e53516ba6d76b12a16286612b9/chart/values.yaml#L119)

**Comment by okdadmin** [comment]
Thank you, but I install in OKD4.13! :)

**Comment by okdadmin** [comment]
Then maybe I can't log in because I'm installing in OKD?

**Comment by davideserio** [comment]
Helm is recommended (it allows you to automate many steps that, when done via YAML, have to be done manually), but you can install Velero UI via YAML with kubectl (there are instructions for each module in the relevant README).

In the case of installing via YAML, you should at least install:

- [velero-api](https://github.com/seriohub/velero-api)
- velero-ui
- [velero-watchdog](https://github.com/seriohub/velero-watchdog) (if necessary)

At the bottom left of the login page, there is a button that provides diagnostic information. Can you share it? Please remove any sensitive information.

Often, the installation errors were due to the misconfiguration of endpoints in the config maps in Velero UI. If you encounter other problems, beyond the diagnostic information, you can share the [Velero UI config map](https://github.com/seriohub/velero-ui/blob/main/k8s/10_config_map.yaml) and [Velero API config map](https://github.com/seriohub/velero-api/blob/main/k8s/10_config_map.yaml) (remove any sensitive information).
