### ISSUE TITLE
Error Oops, something went wrong. SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by SWAGATAM04** [seriohub/velero-ui#43]
When trying to send report from wathcdog getting below error
Error
Oops, something went wrong. SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
![sendreport](https://github.com/user-attachments/assets/55dac491-6fab-402a-9067-19269bd37d90)

Can you please let us know after backup if we can send the report on mail automatically .
Appreciate your help.

**Comment by davideserio** [comment]
The error in the UI screen is a bug that has just been fixed in development, and I hope to release the update soon.
If you used the Helm installation, you can configure the notifications as needed by following the example [values-override.yaml](https://github.com/seriohub/velero-helm/blob/main/values-override.yaml#L56) (_Watchdog Cron_ and _Watchdog Daemon_ sections), you can use mail, telegram or slack. 
Notifications can be sent either on a schedule or after a new backup event is detected. In the https://github.com/seriohub/velero-helm/tree/main/chart file, you'll find description for each key in the [values.yaml](https://github.com/seriohub/velero-helm/blob/main/chart/values.yaml) file.
